### ISSUE TITLE
Lets neem een favicon, misschien kan jordy morgen dat logo in een 16x16 pixel ding maken. Anders doe ik het.

### ISSUE THREAD

**Issue by cunothe1** [nasserievermeij/koffiefonds#11]
Lees de titel

**Comment by jpouw** [comment]
wat is een favicon?

**Comment by jpouw** [comment]
![favicon of zoiets](https://cloud.githubusercontent.com/assets/15103896/12671033/43c60ef4-c66d-11e5-84eb-dbe2303df17f.png) hoooooooooooooooooooooooooooooooiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii als je dit leest wordt je geslagen :+1:

**Comment by cunothe1** [comment]
@jpouw ik heb het gelezen en ik word niet geslagen
