### ISSUE TITLE
kan je dit erin zetten als mobielachtergrond.png

### ISSUE THREAD

**Issue by cunothe1** [nasserievermeij/koffiefonds#8]
http://1.bp.blogspot.com/-qNmpckKEXzE/TsAqBRieBvI/AAAAAAAAAcA/6y1F6D4IYcA/s1600/nva+14112011+2712++amsterdamse+bos-18.jpg

**Comment by noirscape** [comment]
Uploaded, but it's a PNG instead of a JPG.
