### ISSUE TITLE
achtergrond

### ISSUE THREAD

**Issue by jpouw** [nasserievermeij/koffiefonds#9]
![image](https://cloud.githubusercontent.com/assets/15103896/12578280/1a83aab4-c420-11e5-8d64-f5723795c9cf.png)

**Comment by jpouw** [comment]
mentions:cunothe1

**Comment by noirscape** [comment]
![](https://everplaces.com/users/10066deab62c4291afefa395575dffe8/places/710ca4d063044969a6141cef8ff3c7a1/images/648e718521114cc191b18ea54ffb05b4.jpg)
